### PR TITLE
starfive/visionfive: add beaglev and visionfive support

### PR DESCRIPTION
**Pull request by paralin**
Adds support for the RISC-V StarFive VisionFive boards as well as BeagleV (Compatible).

### CODE REVIEW

**Comment by paralin** [comment]
requested & tested by @ clayauld on discord

**Comment by clayauld** [comment]
I put some info on the Discord server, but the build is stopping when it tries to pull the ddrinit tar.gz from the SkiffOS mirror repo. I believe it would be pulling the latest released ddrinit file from here: https://github.com/starfive-tech/JH7100_ddrinit/releases

The relevant info is on the StarFive VisionFive Quick Start Guide in Appendix A and B: https://wiki.rvspace.org/en/Product/VisionFive/Technical_Documents/VisionFive_Single_Board_Computer_Quick_Start_Guide

**Comment by paralin** [comment]
@clayauld it fails the hash check. See your logs you sent. The download hash changed from GitHub since it was added in the buildroot tree.

After the hash check failed it will try to download from the mirror repo as a fallback.

I've updated the hash in the buildroot tree. Please pull this branch and then "git submodule update" and try again

**Comment by clayauld** [comment]
The hash in buildroot/boot/beaglev-secondboot/beaglev-secondboot.hash for beaglev-secondboot-2d20047960044308126117ad56bc08a1164e82b2.tar.gz needs to be updated to 683f017c11d7955b6108c2538313ad3bb546a792fccc6cf01dee62c082516965

**Comment by paralin** [comment]
@clayauld Fixed both 👍🏽

**Comment by paralin** [comment]
Hey @clayauld did you have a chance to test this yet?

**Comment by clayauld** [comment]
Building this works. Still gotta test it on the board. Waiting for my UART to USB converter to arrive from Amazon.

**Comment by clayauld** [comment]
I did get uboot, ddrinit, and second bootloader updated on the board. However, SkiffOS does not seem to boot from the SD card. U-boot seems to start the autoboot process and initialize the sd card appropriately, but nothing happens. The terminal just appears to drop to the U-boot shell.

**Comment by clayauld** [comment]
I'm able to see the files in on the sd card inside the uboot shell, and I tried to run the following commands... I got them from the boot-scripts directory for the visionfive.

```bash
setenv bootargs 'root=PARTUUID=${uuid} rootwait rw init=/boot/skiff-init/skiff-init-squashfs console=ttyS0,115200 earlyprintk fsck.repair=yes net.ifnames=0'
load mmc 0:1 $kernel_addr_r /boot/Image
load mmc 0:1 $fdt_addr_r /boot/jh7100-starfive-visionfive-v1.dtb
bootm $kernel_addr_r - $fdt_addr_r
```

However, it does not appear to be able to boot the kernel image.  Here is the output

```bash
BeagleV # setenv bootargs 'root=PARTUUID=${uuid} rootwait rw init=/boot/skiff-init/skiff-init-squashfs console=ttyS0,115200 earlyprintk fsck.repair=yes net.ifnames=0'
BeagleV # load mmc 0:1 $kernel_addr_r /boot/Image
19746816 bytes read in 4090 ms (4.6 MiB/s)
BeagleV # load mmc 0:1 $fdt_addr_r /boot/jh7100-starfive-visionfive-v1.dtb
21860 bytes read in 13 ms (1.6 MiB/s)
BeagleV # bootm $kernel_addr_r - $fdt_addr_r
Wrong Image Format for bootm command
ERROR: can't get kernel image!
```

**Comment by paralin** [comment]
@clayauld the boot scripts dir just has extlinux.conf - are you sure you're on the latest visionfive branch version from GitHub? Or do you mean that you've written those uboot commands based on extlinux?

It's supposed to scan the drives and find one with extlinux, then load that. Could you possibly paste the uboot logs where it's not finding the extlinux.conf?

As for the commands you tried: perhaps try using "booti" instead of "bootm" to check if that maybe works

Also - if you could printenv kernel_addr_r and printenv fdt_addr_r so we can check those addresses and see if maybe the kernel is overlapping the FDT in memory or vise-versa with the default addresses. 

Thanks

**Comment by clayauld** [comment]
Looks like the boot started but ends in a kernel panic now.

See attached log file.
[boot_error.log](https://github.com/skiffos/SkiffOS/files/8962728/boot_error.log)

**Comment by clayauld** [comment]
Looks like it now starts the boot, then ends in a kernel panic. See attached log file
[boot_error.log](https://github.com/skiffos/SkiffOS/files/8962769/boot_error.log)
.

**Comment by paralin** [comment]
@clayauld It should work if you change the extlinux.conf

```
LABEL SkiffOS
  KERNEL /boot/Image
  FDT /boot/jh7100-starfive-visionfive-v1.dtb
  APPEND root=/dev/mmcblk0p1 rootwait rw init=/boot/skiff-init/skiff-init-squashfs console=ttyS0,115200 earlyprintk fsck.repair=yes net.ifnames=0
```

**Comment by paralin** [comment]
@clayauld 

```
Unable to handle kernel paging request at virtual address 0000007f0139dac0
Oops [#1]
Modules linked in: brcmfmac brcmutil zstd zstd_decompress zstd_compress snd_soc_simple_card snd_soc_simple_card_utils zram snd_soc_starfive_pwmdac snd_soc_starfive_pwmdac_transmitter zsmalloc snd_soc_core snd_pcm_dmaengine snd_pcm cfg80211 snd_timer snd fuse
CPU: 1 PID: 45 Comm: kworker/1:1 Not tainted 5.19.0-rc1-visionfive #1
Hardware name: StarFive VisionFive V1 (DT)
Workqueue: events request_firmware_work_func
epc : brcmf_sdio_bus_txctl+0xc4/0x118 [brcmfmac]
 ra : brcmf_sdio_bus_txctl+0xc4/0x118 [brcmfmac]
epc : ffffffff0139dac0 ra : ffffffff0139dac0 sp : ffffffc80419b8d0
 gp : ffffffff812d48f0 tp : ffffffd88016eb80 t0 : 0000000000046000
 t1 : 0000000000000000 t2 : 00000000000003ff s0 : ffffffc80419b930
 s1 : ffffffd888930000 a0 : 0000000000000271 a1 : 0000000000000002
 a2 : ffffffd9f7dc6e10 a3 : 14c0800000000000 a4 : 0000000000000000
 a5 : ffffffffffffffff a6 : ffffffff812122f8 a7 : 0000000000000001
 s2 : 0000000000000271 s3 : ffffffd8889302f8 s4 : ffffffd88abf07c0
 s5 : ffffffd88abf0960 s6 : 0000000000000000 s7 : 0000000000000106
 s8 : ffffffd88abf4054 s9 : ffffffd88abf0960 s10: ffffffd88abf07c0
 s11: ffffffd88893182c t3 : 0000000000000000 t4 : ffffffff80da7e30
 t5 : d8a722f2be0e6c50 t6 : 0000000000001970
status: 0000000200000120 badaddr: 0000007f0139dac0 cause: 000000000000000c
[<ffffffff01399106>] brcmf_proto_bcdc_msg+0xa8/0xc0 [brcmfmac]
[<ffffffff0139934e>] brcmf_proto_bcdc_query_dcmd+0x40/0x17c [brcmfmac]
[<ffffffff0138fb14>] brcmf_fil_cmd_data+0x4e/0xb0 [brcmfmac]
[<ffffffff01390308>] brcmf_fil_bsscfg_data_get+0x5e/0xc6 [brcmfmac]
[<ffffffff013903b4>] brcmf_fil_bsscfg_int_get+0x20/0x32 [brcmfmac]
[<ffffffff013855aa>] brcmf_construct_chaninfo+0x26e/0x324 [brcmfmac]
[<ffffffff01385734>] brcmf_setup_wiphybands+0xd4/0x462 [brcmfmac]
[<ffffffff0138d9dc>] brcmf_cfg80211_attach+0x29a/0x76a [brcmfmac]
[<ffffffff013960c4>] brcmf_bus_started+0xde/0x31a [brcmfmac]
[<ffffffff01396380>] brcmf_attach+0x80/0x106 [brcmfmac]
[<ffffffff0139f576>] brcmf_sdio_firmware_callback+0x426/0x4c6 [brcmfmac]
[<ffffffff01397060>] brcmf_fw_request_done+0xc2/0x14a [brcmfmac]
[<ffffffff803e0400>] request_firmware_work_func+0x2c/0x50
[<ffffffff80024376>] process_one_work+0x192/0x2c6
[<ffffffff800245bc>] worker_thread+0x112/0x3f4
[<ffffffff8002ac92>] kthread+0x96/0xa8
[<ffffffff80002fba>] ret_from_exception+0x0/0xc
---[ end trace 0000000000000000 ]---
[  OK  ] Reached target Sound Card.
```

seems to have crashed at brcmf_sdio_bus_txctl

... or the firmware loading step

Probably because of:

```
# CONFIG_PREVENT_FIRMWARE_BUILD is not set
CONFIG_EXTRA_FIRMWARE="regulatory.db regulatory.db.p7s brcm/brcmfmac43430-sdio.bin brcm/brcmfmac43430-sdio.clm_blob brcm/brcmfmac43430-sdio.txt"
CONFIG_EXTRA_FIRMWARE_DIR="firmware"
```

I'm preparing a couple patches and will ping you in a few mins when it's ready

**Comment by paralin** [comment]
@clayauld Okay I:

 - enabled the rpi wifi firmware package which has the required files
 - upgraded the kernel to 5.19-rc3
 
Please git pull, git submodule update, delete workspaces/default/build/ dirs linux-custom, linux-headers-custom, glibc*, and delete workspaces/default/extra_images, then run "make configure compile" again.

**Comment by clayauld** [comment]
Here is the latest boot log. Still seems to be locking up. I performed a full clean of the workspace and rebuild.
[visionfive_boot.log](https://github.com/skiffos/SkiffOS/files/8966959/visionfive_boot.log)

**Comment by paralin** [comment]
@clayauld seems to be a lockup in either `addrconf_verify_work` or `ipv6_addrconf`. I suspect it's because extra features are enabled in Skiff that aren't enabled in the visionfive_defconfig, so these bugs haven't been found yet by the kernel developers.

I'm pushing a patch which disables a lot of extra features to bring it closer to the stock visionfive_defconfig.

The full set of changes to the Skiff config to make it identical to the visionfive_defconfig:

```
# CONFIG_6LOWPAN is not set
# CONFIG_AUTOFS4_FS is not set
# CONFIG_BATMAN_ADV is not set
# CONFIG_BINFMT_MISC is not set
# CONFIG_BLK_CGROUP is not set
CONFIG_BLK_DEV_LOOP_MIN_COUNT=1
# CONFIG_BLK_DEV_RAM is not set
CONFIG_BRCMFMAC=y
CONFIG_BRCMUTIL=y
# CONFIG_BRIDGE is not set
CONFIG_BT=y
CONFIG_BTRFS_FS=y
CONFIG_BT_BNEP=y
# CONFIG_BT_BNEP_MC_FILTER is not set
# CONFIG_BT_BNEP_PROTO_FILTER is not set
# CONFIG_BT_HCIBTUSB is not set
CONFIG_BT_HCIUART=y
# CONFIG_BT_HCIVHCI is not set
CONFIG_BT_HIDP=y
CONFIG_BT_RFCOMM=y
CONFIG_CC_VERSION_TEXT="gcc (Gentoo 11.3.0 p4) 11.3.0"
CONFIG_CFG80211=y
# CONFIG_CFG80211_WEXT is not set
# CONFIG_CGROUP_BPF is not set
# CONFIG_CGROUP_DEVICE is not set
# CONFIG_CGROUP_FREEZER is not set
# CONFIG_CGROUP_NET_CLASSID is not set
# CONFIG_CGROUP_NET_PRIO is not set
# CONFIG_CGROUP_PERF is not set
# CONFIG_CHECKPOINT_RESTORE is not set
# CONFIG_CONFIGFS_FS is not set
# CONFIG_CPUSETS is not set
# CONFIG_CRC_CCITT is not set
# CONFIG_CRYPTO_AEGIS128 is not set
# CONFIG_CRYPTO_ANSI_CPRNG is not set
# CONFIG_CRYPTO_AUTHENC is not set
# CONFIG_CRYPTO_BLOWFISH is not set
# CONFIG_CRYPTO_CAST5 is not set
# CONFIG_CRYPTO_CAST6 is not set
# CONFIG_CRYPTO_CBC is not set
# CONFIG_CRYPTO_CCM is not set
# CONFIG_CRYPTO_CHACHA20 is not set
# CONFIG_CRYPTO_CTR is not set
# CONFIG_CRYPTO_CURVE25519 is not set
# CONFIG_CRYPTO_DEFLATE is not set
# CONFIG_CRYPTO_DES is not set
# CONFIG_CRYPTO_DH is not set
# CONFIG_CRYPTO_ECHAINIV is not set
# CONFIG_CRYPTO_GCM is not set
# CONFIG_CRYPTO_GHASH is not set
# CONFIG_CRYPTO_LZ4 is not set
# CONFIG_CRYPTO_LZ4HC is not set
# CONFIG_CRYPTO_LZO is not set
# CONFIG_CRYPTO_MD4 is not set
# CONFIG_CRYPTO_NULL is not set
# CONFIG_CRYPTO_SEQIV is not set
# CONFIG_CRYPTO_SERPENT is not set
# CONFIG_CRYPTO_SHA1 is not set
# CONFIG_CRYPTO_TWOFISH is not set
# CONFIG_CRYPTO_USER is not set
# CONFIG_CRYPTO_USER_API_AEAD is not set
# CONFIG_CRYPTO_USER_API_HASH is not set
# CONFIG_CRYPTO_USER_API_RNG is not set
# CONFIG_CRYPTO_USER_API_SKCIPHER is not set
# CONFIG_CRYPTO_WP512 is not set
CONFIG_CRYPTO_ZSTD=y
# CONFIG_DCB is not set
# CONFIG_DUMMY is not set
CONFIG_EXFAT_FS=y
# CONFIG_EXT2_FS is not set
# CONFIG_EXT3_FS is not set
# CONFIG_FUSE_FS is not set
# CONFIG_INET_DIAG is not set
# CONFIG_INET_ESP is not set
# CONFIG_KEY_DH_OPERATIONS is not set
CONFIG_LZO_COMPRESS=y
CONFIG_LZO_DECOMPRESS=y
# CONFIG_MAC80211 is not set
# CONFIG_MACVLAN is not set
# CONFIG_MEDIA_SUPPORT is not set
# CONFIG_MEMCG is not set
# CONFIG_MISC_FILESYSTEMS is not set
# CONFIG_MODULES is not set
# CONFIG_MPLS is not set
# CONFIG_MSDOS_FS is not set
# CONFIG_NETFILTER is not set
# CONFIG_NETLINK_DIAG is not set
# CONFIG_NET_9P is not set
# CONFIG_NET_CLS_BPF is not set
# CONFIG_NET_CLS_CGROUP is not set
# CONFIG_NET_CLS_FLOW is not set
# CONFIG_NET_CLS_FW is not set
# CONFIG_NET_CLS_MATCHALL is not set
# CONFIG_NET_CLS_ROUTE4 is not set
# CONFIG_NET_CLS_RSVP is not set
# CONFIG_NET_CLS_RSVP6 is not set
# CONFIG_NET_CLS_TCINDEX is not set
# CONFIG_NET_CLS_U32 is not set
# CONFIG_NET_EMATCH is not set
CONFIG_NET_IP_TUNNEL=y
# CONFIG_NET_KEY is not set
# CONFIG_NET_NSH is not set
# CONFIG_NET_SCH_HFSC is not set
# CONFIG_NET_SCH_HTB is not set
# CONFIG_NET_SCH_NETEM is not set
# CONFIG_NET_SCH_PRIO is not set
# CONFIG_NET_SCH_SFQ is not set
# CONFIG_NET_SCH_TAPRIO is not set
# CONFIG_NET_SCH_TBF is not set
# CONFIG_NET_SCH_TEQL is not set
CONFIG_NET_UDP_TUNNEL=y
# CONFIG_OPENVSWITCH is not set
# CONFIG_OVERLAY_FS is not set
# CONFIG_PACKET_DIAG is not set
# CONFIG_PCI is not set
# CONFIG_PROC_CHILDREN is not set
CONFIG_RAID6_PQ=y
# CONFIG_RD_LZ4 is not set
CONFIG_RD_ZSTD=y
CONFIG_REGMAP_SPI=y
CONFIG_SND=y
CONFIG_SND_DMAENGINE_PCM=y
# CONFIG_SND_HRTIMER is not set
CONFIG_SND_PCM=y
# CONFIG_SND_SEQUENCER is not set
CONFIG_SND_SIMPLE_CARD=y
CONFIG_SND_SIMPLE_CARD_UTILS=y
CONFIG_SND_SOC=y
CONFIG_SND_SOC_HDMI_CODEC=y
CONFIG_SND_SOC_I2C_AND_SPI=y
CONFIG_SND_STARFIVE_PWMDAC=y
CONFIG_SND_TIMER=y
# CONFIG_TCG_TPM is not set
# CONFIG_TCP_CONG_ADVANCED is not set
# CONFIG_UHID is not set
# CONFIG_USB_ACM is not set
# CONFIG_USB_CATC is not set
# CONFIG_USB_EZUSB_FX2 is not set
# CONFIG_USB_GADGET is not set
# CONFIG_USB_KAWETH is not set
# CONFIG_USB_SERIAL is not set
# CONFIG_USB_STORAGE_CYPRESS_ATACB is not set
# CONFIG_USB_STORAGE_ENE_UB6250 is not set
# CONFIG_USB_STORAGE_REALTEK is not set
# CONFIG_USB_STORAGE_SDDR55 is not set
# CONFIG_USB_STORAGE_USBAT is not set
CONFIG_USB_UAS=y
# CONFIG_USER_NS is not set
# CONFIG_VETH is not set
# CONFIG_VIRTIO_CONSOLE is not set
# CONFIG_VSOCKETS is not set
# CONFIG_VXLAN is not set
CONFIG_WIREGUARD=y
# CONFIG_XFRM_USER is not set
# CONFIG_XZ_DEC is not set
CONFIG_ZLIB_DEFLATE=y
CONFIG_ZRAM=y
# CONFIG_ZRAM_WRITEBACK is not set
CONFIG_ZSMALLOC=y
# CONFIG_ZSMALLOC_STAT is not set
CONFIG_ZSTD_COMPRESS=y
CONFIG_ZSTD_DECOMPRESS=y
CONFIG_DECOMPRESS_ZSTD=y
CONFIG_EXT4_USE_FOR_EXT2=y
```

I've dropped some of these for the patch included in this PR

**Comment by paralin** [comment]
@clayauld pushed the change. Looking forward to hearing how it goes, when you are next able to test.

```
git fetch
git reset --hard origin/visionfive
git submodule update
```

Not needed to fully rebuild, you can delete extra_images and build/linux-custom only and it should be fine.

**Comment by clayauld** [comment]
After the latest changes the system successfully booted.

image

**Comment by clayauld** [comment]
However, after connecting to core it seems there's an issue as its setting up the core docker container. I'm not sure if Chromium has been built for RISC-V yet, but it seems that's keeping it from completing.

```
Removing intermediate container e054f156fbf6                                                                                                                                                                         
Image setup failed with error:                                                                                                                                                                                       
The command '/bin/sh -c apt-get dist-upgrade -y &&     apt-get install -y      --no-install-recommends     -o "Dpkg::Options::=--force-confdef"      -o "Dpkg::Options::=--force-confnew"      autotools-dev     buil
d-essential     chromium     cups     curl     git     htop     less     lightdm     locales     lsb-release     mesa-utils     nano     ncurses-term     net-tools     openssh-client     rsync     software-propert
ies-common     sudo     systemd     task-xfce-desktop     unzip     usbutils     vim     wget     x11vnc' returned a non-zero code: 100                                                                              
2022/06/27 16:50:18 Re-opening truncated file /home/core/.skiff-core-setup.log ...                                                                                                                                   
2022/06/27 16:50:18 Successfully reopened truncated /home/core/.skiff-core-setup.log                                                                                                                                 
latest: Pulling from skiffos/skiff-core-debian                                                                                                                                                                       
Step 1/15 : ARG DISTRO                                                                                                                                                                                               
Step 2/15 : FROM ${DISTRO:-debian:sid} as stage1                                                                                                                                                                     
 ---> faf6a9a03d5b                                                                                                                                                                                                   
Step 3/15 : ENV LANG=C.UTF-8     LC_ALL=en_US.UTF-8     DEBIAN_FRONTEND=noninteractive     container=docker                                                                                                          
 ---> Using cache                                                                                                                                                                                                    
 ---> 5c4737f6bdc5                                                                                                                                                                                                   
Step 4/15 : RUN rm -rf /var/lib/apt/lists/* &&     apt-get update                                                                                                                                                    
 ---> Using cache                                                                                                                                                                                                    
 ---> 381b2401225a                                                                                                                                                                                                   
Step 5/15 : RUN     apt-get dist-upgrade -y &&     apt-get install -y      --no-install-recommends     -o "Dpkg::Options::=--force-confdef"      -o "Dpkg::Options::=--force-confnew"      autotools-dev     build-es
sential     chromium     cups     curl     git     htop     less     lightdm     locales     lsb-release     mesa-utils     nano     ncurses-term     net-tools     openssh-client     rsync     software-properties-
common     sudo     systemd     task-xfce-desktop     unzip     usbutils     vim     wget     x11vnc                                                                                                                 
 ---> Running in 0e99714c9dce                                                                                                                                                                                        
Reading package lists...                                                                                                                                                                                             
Building dependency tree...                                                                                                                                                                                          
Reading state information...                                                                                                                                                                                         
Calculating upgrade...                                                                                                                                                                                               
The following packages will be upgraded:                                                                                                                                                                             
  libcap-ng0                                                                                                                                                                                                         
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                                                                                                                                                       
Need to get 17.5 kB of archives.                                                                                                                                                                                     
After this operation, 7168 B of additional disk space will be used.                                                                                                                                                  
Get:1 http://deb.debian.org/debian-ports sid/main riscv64 libcap-ng0 riscv64 0.8.3-1 [17.5 kB]                                                                                                                       
perl: warning: Setting locale failed.                                                                                                                                                                                
perl: warning: Please check that your locale settings:                                                                                                                                                               
        LANGUAGE = (unset),                                                                                                                                                                                          
        LC_ALL = "en_US.UTF-8",                                                                                                                                                                                      
        LANG = "C.UTF-8"                                                                                                                                                                                             
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
debconf: delaying package configuration, since apt-utils is not installed
Fetched 17.5 kB in 0s (63.9 kB/s)
(Reading database ... 6614 files and directories currently installed.)
Preparing to unpack .../libcap-ng0_0.8.3-1_riscv64.deb ...
Unpacking libcap-ng0:riscv64 (0.8.3-1) over (0.7.9-4) ...
Setting up libcap-ng0:riscv64 (0.8.3-1) ...
Processing triggers for libc-bin (2.33-7) ...
Reading package lists...
Building dependency tree...
Reading state information...
Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  chromium-bsu

E: Package 'chromium' has no installation candidate
Removing intermediate container 0e99714c9dce
Image setup failed with error:
The command '/bin/sh -c apt-get dist-upgrade -y &&     apt-get install -y      --no-install-recommends     -o "Dpkg::Options::=--force-confdef"      -o "Dpkg::Options::=--force-confnew"      autotools-dev     buil
d-essential     chromium     cups     curl     git     htop     less     lightdm     locales     lsb-release     mesa-utils     nano     ncurses-term     net-tools     openssh-client     rsync     software-propert
ies-common     sudo     systemd     task-xfce-desktop     unzip     usbutils     vim     wget     x11vnc' returned a non-zero code: 100
2022/06/27 16:51:15 Re-opening truncated file /home/core/.skiff-core-setup.log ...
2022/06/27 16:51:15 Successfully reopened truncated /home/core/.skiff-core-setup.log
latest: Pulling from skiffos/skiff-core-debian
Step 1/15 : ARG DISTRO
Step 2/15 : FROM ${DISTRO:-debian:sid} as stage1
 ---> faf6a9a03d5b
Step 3/15 : ENV LANG=C.UTF-8     LC_ALL=en_US.UTF-8     DEBIAN_FRONTEND=noninteractive     container=docker
 ---> Using cache
 ---> 5c4737f6bdc5
Step 4/15 : RUN rm -rf /var/lib/apt/lists/* &&     apt-get update
 ---> Using cache
 ---> 381b2401225a
Step 5/15 : RUN     apt-get dist-upgrade -y &&     apt-get install -y      --no-install-recommends     -o "Dpkg::Options::=--force-confdef"      -o "Dpkg::Options::=--force-confnew"      autotools-dev     build-es
sential     chromium     cups     curl     git     htop     less     lightdm     locales     lsb-release     mesa-utils     nano     ncurses-term     net-tools     openssh-client     rsync     software-properties-
common     sudo     systemd     task-xfce-desktop     unzip     usbutils     vim     wget     x11vnc
 ---> Running in 3ff13a2eb234
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  libcap-ng0
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 17.5 kB of archives.
After this operation, 7168 B of additional disk space will be used.
Get:1 http://deb.debian.org/debian-ports sid/main riscv64 libcap-ng0 riscv64 0.8.3-1 [17.5 kB]
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
debconf: delaying package configuration, since apt-utils is not installed
Fetched 17.5 kB in 0s (79.2 kB/s)
(Reading database ... 6614 files and directories currently installed.)
Preparing to unpack .../libcap-ng0_0.8.3-1_riscv64.deb ...
Unpacking libcap-ng0:riscv64 (0.8.3-1) over (0.7.9-4) ...
Setting up libcap-ng0:riscv64 (0.8.3-1) ...
Processing triggers for libc-bin (2.33-7) ...
Reading package lists...
Building dependency tree...
Reading state information...
Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  chromium-bsu
```

**Comment by paralin** [comment]
@clayauld could you please try with core/gentoo or edit the dockerfile in /opt/skiff/core (somewhere in there) and remove the chromium lines?

**Comment by paralin** [comment]
@clayauld thanks again for testing. I've added --ignore-missing to the core defconfig which should have it skip the missing packages (chromium) in future. I'm also updating the debian image to have riscv as well.

Merging this, please open new issues if you run into any more problems! Thanks again!

**Comment by clayauld** [comment]
Excellent! I'll definitely update you on any other issues that may come up.

**Pull request merged**
