### PR TITLE
wsl: start init process with wsl-shell

### LINKED ISSUE #213: WSL: timed out waiting for init process to start
After building SkiffOS for WSL and importing the tar.gz archive according to the guide, the system will not start. The error are shown in the screenshot.

I have confirmed that I imported the archive as WSL version 2.

image

### PR DESCRIPTION
**Pull request by paralin**
Fixes #213 

Needs testing.

### CODE REVIEW

**Comment by clayauld** [comment]
I tried compiling from the fix-wsl branch. I'm getting an issue with aircrack-ng
image

**Comment by paralin** [comment]
@clayauld Please pull & try now.

**Comment by clayauld** [comment]
Success! 
image

**Comment by paralin** [comment]
@clayauld awesome, got it first try!

Could you please confirm that running multiple instances of wsl.exe start up correctly & that there's not duplicate "systemd" instances in "ps -aux" ?

By the way; you can upgrade this remotely with push_image.sh over ssh same as the other targets. There's a "wsl.exe --shutdown" command which forces reboot if needed.

**Comment by clayauld** [comment]
Here is the output from ```ps -a```
image

I also tried some of the ```wslu``` utilities and it seems ```wslpath``` isn't working (not installed) and some of the InteropServer things don't work.

image

image

Not sure if this is a real problem, but it may create some interesting issues down the road if this was to be used as more than just a testing system.

**Comment by paralin** [comment]
Thanks. Probably there are 1-2 paths that should be added to the bind mount list for skiff-init-squashfs. 

Feel free to open another issue about that specifically, I'll follow up on it either way this evening.

**Pull request merged**
