### PR TITLE
beaglebone: support ai, black, x15

### PR DESCRIPTION
**Pull request by paralin**
Adds support for [BeagleBone AI](https://beagleboard.org/ai)

### CODE REVIEW

**Comment by paralin** [comment]
Before merge:

 - Test against hardware
 - Re-add missing beaglebone/black package

**Comment by paralin** [comment]
Updated to use squashfs boot and mainline u-boot + kernel.

**Comment by paralin** [comment]
Everything builds + installs to the SD correctly but for whatever reason the BeagleBone is booting from on-board storage instead of the SD. I don't have the special uart debug cable on hand at the moment to debug it.

**Comment by paralin** [comment]
I've confirmed that my SD card reader on the Beaglebone AI is broken, I have a new one coming tomorrow, but in the meantime this "should work."

**Comment by jim255** [comment]
I have an AI sitting on my bench doing nothing... would gladly test, but I have no beagle configs.

**Comment by paralin** [comment]
@jim255 After a LOT of trial and error I finally have it working on the Beaglebone AI:

image

Will test on the black soon.

**Comment by jim255** [comment]
I just had a failure building  Beagle-AI  
(tail end of log)

>>> am33x-cm3 11107db2f1e9e58ee75d4fe9cc38423c9a6e4365 Downloading
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git init . 
Reinitialized existing Git repository in /media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git/
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git remote set-url origin 'http://arago-project.org/git/projects/am33x-cm3.git' 
Fetching all references
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git fetch origin 
fatal: unable to access 'http://arago-project.org/git/projects/am33x-cm3.git/': Failed to connect to arago-project.org port 80 after 129807 ms: Connection timed out
Detected a corrupted git cache.
Removing it and starting afresh.
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git init . 
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git/
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git remote add origin 'http://arago-project.org/git/projects/am33x-cm3.git' 
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git remote set-url origin 'http://arago-project.org/git/projects/am33x-cm3.git' 
Fetching all references
GIT_DIR=/media/janderso/_Exp/Projects/SkiffOS/buildroot/dl/am33x-cm3/git/.git git fetch origin 
fatal: unable to access 'http://arago-project.org/git/projects/am33x-cm3.git/': Failed to connect to arago-project.org port 80 after 130243 ms: Connection timed out
Detected a corrupted git cache.
This is the second time in a row; bailing out
wget --passive-ftp -nd -t 3 -O '/media/janderso/_Exp/Projects/SkiffOS/workspaces/beagle_ai/build/.am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365-br1.tar.gz.EaZrir/output' 'https://github.com/skiffos/mirror/raw/master/am33x-cm3/am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365-br1.tar.gz' 
--2022-11-21 17:58:20--  https://github.com/skiffos/mirror/raw/master/am33x-cm3/am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365-br1.tar.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-21 17:58:21 ERROR 404: Not Found.

wget --passive-ftp -nd -t 3 -O '/media/janderso/_Exp/Projects/SkiffOS/workspaces/beagle_ai/build/.am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365-br1.tar.gz.Sl1l0a/output' 'https://github.com/skiffos/mirror/raw/master/am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365-br1.tar.gz' 
--2022-11-21 17:58:21--  https://github.com/skiffos/mirror/raw/master/am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365-br1.tar.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-21 17:58:21 ERROR 404: Not Found.

make[3]: *** [package/pkg-generic.mk:189: /media/janderso/_Exp/Projects/SkiffOS/workspaces/beagle_ai/build/am33x-cm3-11107db2f1e9e58ee75d4fe9cc38423c9a6e4365/.stamp_downloaded] Error 1
make[2]: *** [Makefile:23: _all] Error 2
make[2]: Leaving directory '/media/janderso/_Exp/Projects/SkiffOS/workspaces/beagle_ai'
make[1]: *** [Makefile:64: compile] Error 2
make[1]: Leaving directory '/media/janderso/_Exp/Projects/SkiffOS/build'
make: *** [Makefile:2: compile] Error 2


--Jim

**Comment by paralin** [comment]
@jim255 looks like arango-project site is offline.

I mirrored that file (so the current build will work) but also updated master to point to the buildroot sources and not try the offline server.

```
git checkout master
git pull
git submodule update
```

Then try again. Thanks for the report!

**Pull request merged**
